### ISSUE TITLE
SSHFS is not available

### ISSUE THREAD

**Issue by wickedsp1d3r** [dstuecken/sshfs-gui#1]
I have SSHFS and OSXFUSE installed through [Homebrew Cask](http://caskroom.io), but I still get this message:

![err](https://cloud.githubusercontent.com/assets/1852854/5304118/47758fc2-7bf8-11e4-8165-06676ebe4271.png)

**Comment by phloggu** [comment]
I get the same dialog having installed sshfs through macports. The sshfs binary is in the path and still I see that dialog box. I read the prerequisites for your software, so its a feature request, that it works with a version of sshfs that is in the path.

I would like to use your software but I do not install the same program twice since I like my software being up to date, which I can do with macports easily but not with tons of manually installed software.

**Comment by dstuecken** [comment]
Your issue should be fixed with the latest version: https://github.com/dstuecken/sshfs-gui/raw/develop/Installer/sshfs-gui-1.3.dmg :-)

**Comment by phloggu** [comment]
Dear Dennis

Thank you for considering my feature request. Did you intentionally compile this application for OS X 10.10 and above? I get an error trying to execute the binary on OS X 10.9.

Best regards, Adrian.

**Comment by dstuecken** [comment]
Oh yea sorry, I just recompiled it, does it work now with 10.9?

**Comment by phloggu** [comment]
perfectly!

Thanks a lot!

Best regards, Adrian.
